package main

import (
	"crypto/tls"
	"flag"
	"fmt"
	"io"
	"log"
	"net"
	"os"
)

func main() {
	port := flag.String("port", "8360", "listening port")
	certFile := flag.String("cert", "../testdata/example-cert.pem", "certificate PEM file")
	keyFile := flag.String("key", "../testdata/example-key.pem", "key PEM file")
	keyLogFilePath := flag.String("log", "../log/tls.log", "tls key log path")
	flag.Parse()
	cert, err := tls.LoadX509KeyPair(*certFile, *keyFile)
	if err != nil {
		log.Fatal(err)
	}

	keyLogFile, _ := os.OpenFile(*keyLogFilePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	fmt.Fprintf(keyLogFile, "# SSL/TLS secrets log file, generated by go\n")

	config := &tls.Config{
		Certificates: []tls.Certificate{cert},
		KeyLogWriter: keyLogFile,
	}
	log.Printf("listening on port %s\n", *port)
	l, err := tls.Listen("tcp4", ":"+*port, config)
	if err != nil {
		log.Fatal(err)
	}
	defer l.Close()
	for {
		conn, err := l.Accept()
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("accepted connection from %s\n", conn.RemoteAddr())
		go func(c net.Conn) {
			io.Copy(c, c)
			c.Close()
			log.Printf("closing connection from %s\n", conn.RemoteAddr())
		}(conn)
	}

}
